In [1]:
import numpy as np
np.version.full_version

'1.18.5'

In [2]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
np.ndarray

numpy.ndarray

In [6]:
b = a.reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
a.ndim

1

In [8]:
a.shape

(20,)

In [9]:
type(a)

numpy.ndarray

In [10]:
a.dtype

dtype('int32')

In [11]:
c = [i for i in range(10)]
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
d = np.array(c)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b1 = b+1
b1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
b2 = b + 2
b2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [16]:
np.exp(d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.sqrt(d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
d.sum()

45

In [28]:
b.sum(axis = 1)

array([10, 35, 60, 85])

In [29]:
c = np.matrix(b)
c

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [30]:
type(c)

numpy.matrix

In [33]:
d = np.asmatrix(b)

In [35]:
d = d.reshape(5,4)
d

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
e = c*d
e

matrix([[120, 130, 140, 150],
        [320, 355, 390, 425],
        [520, 580, 640, 700],
        [720, 805, 890, 975]])

In [41]:
e[0]
"""
注意,matrix的元素访问和array的元素访问不同
e是matrix,e[0]依然是matrix,无法出现e[0][1]的情况
而array可以
b是array
b[0][1] = 1

"""

matrix([[120, 130, 140, 150]])

In [45]:
b[0][1]

1

In [46]:
f = b
f[0][1] = 100
print(f)
print(b)

[[  0 100   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[  0 100   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [47]:
"""
Python不是真正将 a 复制一份给 b ，
而是将 b 指到了 a 对应数据的内存地址上。想要真正的复制一份 a 给 b ，可
以使用 copy
"""
f = b.copy()
f[0][1] = 10
print(f)
print(b)

[[ 0 10  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[  0 100   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [48]:
"""
Python不是真正将 a 复制一份给 b ，
而是将 b 指到了 a 对应数据的内存地址上。想要真正的复制一份 a 给 b ，可
以使用 copy
"""
f = b.copy()
b[0][1] = 20
print(f)
print(b)

[[  0 100   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[ 0 20  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [52]:
g = np.arange(20).reshape(4, 5)
g[:,[1,3]]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [54]:
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
# 切片
print(g[1,2])
# 可以看到,1,表示第2行,2表示第3列;
print(g[:,2])
# g[:,2],取每一行的第3列

7
[ 2  7 12 17]


In [60]:
# g[:,2]是numpy.ndarray, 可以根据boolean条件切片
print(type(g[:,2]))
print(g[:,2][g[:,2] > 10])

<class 'numpy.ndarray'>
[12 17]


In [63]:
# where查询特定值在数组中的位置
loc = np.where(g == 11)
loc

(array([2], dtype=int64), array([1], dtype=int64))

In [64]:
type(loc)

tuple

In [67]:
# 注意loc的数据结构
g[loc[0][0], loc[1][0]]

11

In [69]:
# 数组操作
aa = np.random.rand(2, 4)
aa

array([[0.06013223, 0.34011483, 0.89752447, 0.75909822],
       [0.2615653 , 0.02118423, 0.79592385, 0.00694068]])

In [70]:
ab = aa.transpose()
ab

array([[0.06013223, 0.2615653 ],
       [0.34011483, 0.02118423],
       [0.89752447, 0.79592385],
       [0.75909822, 0.00694068]])

In [77]:
ac = np.arange(2, 45, 3).reshape(5, 3)
ad = ac.reshape(3, 5)
print(ac, ad)

[[ 2  5  8]
 [11 14 17]
 [20 23 26]
 [29 32 35]
 [38 41 44]] [[ 2  5  8 11 14]
 [17 20 23 26 29]
 [32 35 38 41 44]]


In [79]:
np.mat(ac) *np.mat(ad)

matrix([[ 345,  390,  435,  480,  525],
        [ 804,  930, 1056, 1182, 1308],
        [1263, 1470, 1677, 1884, 2091],
        [1722, 2010, 2298, 2586, 2874],
        [2181, 2550, 2919, 3288, 3657]])

In [80]:
np.mat(aa) *np.mat(ab)

matrix([[1.50107426, 0.74256336],
        [0.74256336, 0.70240812]])

In [81]:
np.matrix(aa) * np.matrix(ab)

matrix([[1.50107426, 0.74256336],
        [0.74256336, 0.70240812]])

In [82]:
"""
两种矩阵乘法写法
np.mat(aa) *np.mat(ab)
np.matrix(aa) * np.matrix(ab)
np.asmatrix(aa) * np.asmatrix(ab)
"""
type(np.matrix(aa))

numpy.matrix

In [85]:
temp = np.asmatrix(aa)
print(type(temp))
temp2 = np.matrix(aa)
print(type(temp2))

<class 'numpy.matrix'>
<class 'numpy.matrix'>


In [87]:
np.asmatrix(ac) * np.asmatrix(ad)

matrix([[ 345,  390,  435,  480,  525],
        [ 804,  930, 1056, 1182, 1308],
        [1263, 1470, 1677, 1884, 2091],
        [1722, 2010, 2298, 2586, 2874],
        [2181, 2550, 2919, 3288, 3657]])

In [90]:
# 求逆矩阵,Last 2 dimensions of the array must be square,需要square
ae = np.random.rand(2,2)
ae

array([[0.68970394, 0.86317187],
       [0.63198999, 0.67019265]])

In [91]:
np.linalg.inv(ae)

array([[-8.04732067, 10.36451355],
       [ 7.58860318, -8.28160197]])