In [1]:
import numpy as np
import scipy.stats as stats
import scipy.optimize as opt

In [2]:
rv_unif = stats.uniform.rvs(size = 10)
rv_unif

array([0.00799052, 0.96879882, 0.9657342 , 0.13585039, 0.74493787,
       0.2300573 , 0.07872845, 0.37811787, 0.68701066, 0.0268473 ])

In [3]:
# 这里的a和b是beta函数中的参数
rv_beta = stats.beta.rvs(size = 10, a = 4, b = 2)
rv_beta

array([0.43194722, 0.78087186, 0.85903357, 0.88344811, 0.89724661,
       0.13652592, 0.77214159, 0.68723883, 0.68957703, 0.56551681])

In [10]:
rv_beta = stats.beta.rvs(size = 10, a = 1, b = 2)
rv_beta

array([0.10611622, 0.41323752, 0.18251284, 0.11845887, 0.13177617,
       0.30332205, 0.14895052, 0.11094247, 0.13184648, 0.51039478])

In [11]:
norm_dist = stats.norm(loc = 0.5, scale = 2)
n = 200
data = norm_dist.rvs(size = n)
data

array([ 2.79098788e+00,  1.03937034e+00,  1.72352690e-01, -1.58301614e+00,
        9.18996818e-01, -2.22749050e+00,  7.70609579e-01,  1.50791809e+00,
       -5.09164349e-01, -8.46005015e-01,  2.74443956e+00,  2.60847685e-01,
        1.02980237e+00, -9.40505138e-01, -1.22283568e+00,  1.42923987e+00,
        2.52929311e+00,  3.31566834e+00,  1.22269229e+00,  2.12514481e+00,
        1.33511193e+00, -1.92049792e+00,  3.05642652e+00,  3.09131372e-01,
        7.30390334e-02,  2.86321523e+00, -2.04682358e+00,  1.10465327e+00,
        2.30471230e+00,  3.50631682e-01,  1.32306301e+00,  6.72915421e-01,
       -5.18413629e+00,  2.44079267e+00, -5.18474893e-01, -3.73449181e+00,
       -1.77535479e-01, -8.59385906e-01,  4.32808322e+00,  8.12095259e-01,
       -2.02082920e+00, -4.29890108e-02, -9.54291895e-01, -2.00505786e-01,
        1.93765843e+00, -3.85985643e+00,  5.89333936e-02,  3.28023159e+00,
        1.74138119e+00,  7.75306842e-01, -2.67764900e+00, -1.27801117e+00,
       -8.74658924e-02,  

In [12]:
print(np.mean(data), np.std(data), np.median(data))

0.39530962471988956 1.8264106785995375 0.5454809081814961


In [13]:
mu = np.mean(data)
sigma = np.std(data)
stat_val, p_val = stats.kstest(data, 'norm', (mu, sigma))
print(stat_val, p_val)

0.04173112745927843 0.8770283757202693


In [14]:
stat_val, p_val = stats.ttest_1samp(data, 0)
print(stat_val, p_val)

3.0532719565679924 0.0025730327685911866


In [24]:
norm_dist2 = stats.norm(loc=-0.2, scale=1.2)
data2 = norm_dist2.rvs(size=n)

In [25]:
data2.shape

(200,)

In [26]:
data.shape

(200,)

In [27]:
stat_val, p_val = stats.ttest_ind(data2, data, equal_var=False)
print(stat_val, p_val)

-4.2372329290741515 2.9044455129801155e-05


In [28]:
g_dist = stats.gamma(a = 2)
g_dist.cdf([2,4,5])

array([0.59399415, 0.90842181, 0.95957232])

In [29]:
g_dist

In [31]:
type(g_dist)

scipy.stats._distn_infrastructure.rv_frozen

In [32]:
g_dist.a

0.0

In [33]:
norm_dist = stats.norm(loc=0, scale=1.8)
dat = norm_dist.rvs(size=100)
info = stats.describe(dat)
str(info[0])

'100'

In [34]:
info

DescribeResult(nobs=100, minmax=(-4.124906800176572, 3.8696073473769057), mean=-0.2750681463843731, variance=2.733533310351098, skewness=0.15986591492434218, kurtosis=-0.31863338809955444)

In [35]:
x = stats.chi2.rvs(3, size=50)
y = 2.5 + 1.2 * x + stats.norm.rvs(size=50, loc=0, scale=1.5)
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)
print(slope, intercept, r_value, p_value, std_err)

1.1968299359381585 2.4932263467306144 0.9106244103912621 4.735967920165555e-20 0.07839162332709211
