In [2]:
import pandas as pd
import numpy as np
np_list = np.arange(10000)

%timeit np_list ** 2

7.04 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
normal_list = range(10000)
%timeit [i**2 for i in normal_list]

2.91 ms ± 19.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
"""
numpy底层通过使用C语言和Fortran语言的机制分配内存,可以理解为它的输出是一个非常大的连续的并且由同类型数据组成的内存区域
所以你可以构造一个比普通列表大得多的数组,并且灵活高效对数组中所有元素进行并行化操作
"""

'\nnumpy底层通过使用C语言和Fortran语言的机制分配内存,可以理解为它的输出是一个非常大的连续的并且由同类型数据组成的内存区域\n所以你可以构造一个比普通列表大得多的数组,并且灵活高效对数组中所有元素进行并行化操作\n'

In [5]:
np_list = np.ones(5) * 3
np_list

array([3., 3., 3., 3., 3.])

In [6]:
#普通的列表把*3认为是整体性操作
normal_list = [1,1,1,1,1] * 3
normal_list

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [8]:
# 3.1.2 初始化操作
a = np.zeros(100)
print(a)

b = np.zeros((3,2))
print(b)

c = np.ones((3,2))
print(c)

d = np.empty((2,3,3))
print(d)

e = np.ones_like(np_list)
print(e)

f = np.zeros_like(np_list)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.33511018e-306 8.06640627e-308 1.33508845e-306]
  [1.33511969e-306 6.23037996e-307 6.23053954e-307]]

 [[9.34609790e-307 8.45593934e-307 9.34600963e-307]
  [2.22523004e-306 1.78021527e-306 6.23059726e-307]
  [1.33511562e-306 6.89805151e-307 1.11261909e-306]]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [10]:
# linspace,从0到1,取20个数据
a = np.linspace(0,1,20)
print(a)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [11]:
# 股票数量
stock_cnt = 200
# 504个交易日
view_days = 504
# 生成服从正态分布的均值期望=0,标准差=1的序列
stock_day_change = np.random.standard_normal((stock_cnt, view_days))
# 打印
print(stock_day_change.shape)
# 打印第一只股票的前5个交易日的涨跌幅情况
print(stock_day_change[0:1, :5])

(200, 504)
[[ 0.30977202 -1.49913026 -1.05440804 -0.04367836 -1.84499436]]


In [16]:
print(stock_day_change[0].shape)
print(stock_day_change[0])
# 先列,后行

(504,)
[ 3.09772023e-01 -1.49913026e+00 -1.05440804e+00 -4.36783628e-02
 -1.84499436e+00 -6.05154281e-01 -2.43652218e-01  2.79176290e+00
  2.13736250e-01 -1.64449731e-01 -6.52240334e-02  1.65494846e-01
 -7.70329245e-02 -9.25997506e-01  5.47302993e-01  1.72923344e+00
  9.48359589e-01  5.10709993e-01 -3.01246952e-01  8.20915203e-01
 -1.17922811e+00 -4.83493014e-01 -5.15183236e-01 -3.65628486e-02
  2.24040011e+00  8.02634773e-01 -1.23674450e+00 -4.64641802e-01
  1.57247861e+00  6.22443233e-01  6.59947646e-01  8.95923872e-02
  5.37129390e-01 -1.59268163e+00 -6.56314853e-01  1.11323633e+00
 -3.88008329e-01 -1.04192395e+00  5.86048944e-01 -9.85268694e-01
  1.08849122e-01 -2.08228827e-01 -2.34261975e+00 -5.48374987e-01
  1.07164082e+00 -5.29347089e-01  1.66276969e+00  4.20179528e-01
  8.32132064e-01  8.25093344e-01 -5.76884117e-01 -4.51565245e-01
  1.14366245e+00  5.11534857e-02  9.28442206e-01  1.60859492e+00
  1.28486327e+00  1.03563853e+00 -7.44401533e-02 -2.54384975e-01
 -1.28791052e+00 -